server:
  name: "notary.codes"
  host: "0.0.0.0"
  port: 7047
  html_info: |
    <head>
    <meta charset="UTF-8">
    <meta name="description" content="mpc-tls">
    <meta name="keywords" content="tlsnotary, mpc, free">
    <meta name="author" content="notary">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
  body {
    font-family: Arial, sans-serif;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    background-color: #f5f5f5;
    margin: 0;
  }

  .code-container {
    position: relative;
    width: 100%;
    max-width: 600px;
    border: 1px solid #ddd;
    border-radius: 5px;
    background-color: #2d2d2d;
    color: #ffffff;
    padding: 15px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
  }

  .code-block {
    font-family: monospace;
    font-size: 0.9em;
    line-height: 1.5;
    white-space: pre-wrap;
    word-break: break-all;
    background-color: #2d2d2d;
    padding: 10px;
    border-radius: 5px;
    overflow-x: auto;
  }

  .copy-button {
    position: absolute;
    top: 10px;
    right: 10px;
    padding: 5px 10px;
    border: none;
    border-radius: 5px;
    background-color: #4caf50;
    color: #ffffff;
    font-size: 0.8em;
    cursor: pointer;
    transition: background-color 0.2s ease;
  }

  .copy-button:hover {
    background-color: #45a049;
  }
</style>
    </head>
    <body>
    <svg width="86" height="88" viewBox="0 0 86 88" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path d="M25.5484 0.708986C25.5484 0.17436 26.1196 -0.167376 26.5923 0.0844205L33.6891 3.86446C33.9202 3.98756 34.0645 4.22766 34.0645 4.48902V9.44049H37.6129C38.0048 9.44049 38.3226 9.75747 38.3226 10.1485V21.4766L36.1936 20.0606V11.5645H34.0645V80.9919C34.0645 81.1134 34.0332 81.2328 33.9735 81.3388L30.4251 87.6388C30.1539 88.1204 29.459 88.1204 29.1878 87.6388L25.6394 81.3388C25.5797 81.2328 25.5484 81.1134 25.5484 80.9919V0.708986Z" fill="#243F5F"/>
    <path d="M21.2903 25.7246V76.7012H12.7742V34.2207H0V25.7246H21.2903Z" fill="#243F5F"/>
    <path d="M63.871 76.7012H72.3871V34.2207H76.6452V76.7012H85.1613V25.7246H63.871V76.7012Z" fill="#243F5F"/>
    <path d="M38.3226 25.7246H59.6129V34.2207H46.8387V46.9649H59.6129V76.7012H38.3226V68.2051H51.0968V55.4609H38.3226V25.7246Z" fill="#243F5F"/>
    </svg>
    <h1>notary server :: at your service</h1>
    <h3>tlsnotary {version}</h3>
    <blink>{public_key}</blink>
    <h4>check to see if the TEE measurement matches the one github signed:</h4>
    <a href="https://github.com/tlsnotary/tlsn/releases/download/{version}/{version}.sbom.spdx.json">github build artifact available here</a>
    <h4>or, compile the notary server and see if the values match (no tee hardware needed!):</h4>
    <div class="code-container">
    <pre class="code-block" id="bash-code">
      git clone -b {version] https://github.com/tlsnotary/tlsn
      cd tlsn/crates/notary/server/tee
      make start-gramine-server
    </pre>
  <button class="copy-button" onclick="copyCode()">Copy</button>
</div>

<script>
  function copyCode() {
    const codeText = document.getElementById("bash-code").innerText;
    navigator.clipboard.writeText(codeText).then(() => {
      alert("Code copied to clipboard!");
    }).catch(err => {
      console.error("Failed to copy text: ", err);
    });
  }
</script>

    </body>

notarization:
  max_sent_data: 4096
  max_recv_data: 16384
  timeout: 1800


tls:
  enabled: false
  private_key_pem_path: "."
  certificate_pem_path: "."

notary_key:
  private_key_pem_path: "/ephemeral/notary.key"
  public_key_pem_path: "/ephemeral/notary.pub"

logging:
  level: INFO

authorization:
  enabled: false
  whitelist_csv_path: "."
